[package]
name = "nyoom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = { version = "0.6.2", features = ["issue-url"] }
crossbeam = { version = "0.8.2", features = ["crossbeam-deque", "crossbeam-queue"] }
eyre = "0.6.8"
libc = "0.2.138"
num_cpus = "1.14.0"

[profile.release]
debug = true
